//
// DO NOT EDIT MANUALLY | THIS FILE WAS GENERATED BY https://github.com/SilverAndro/qkl_math_codegen
//

package org.quiltmc.qkl.library.math

import net.minecraft.util.math.BlockPos
import org.joml.Vector3i
import net.minecraft.util.math.Vec3i

//region Standard math operators
/**
 * Adds a [BlockPos] to a [BlockPos].
 */
public operator fun BlockPos.plus(other: BlockPos): BlockPos {
    return BlockPos(
        this.x + other.x,
        this.y + other.y,
        this.z + other.z
    )
}

/**
 * Subtracts a [BlockPos] from a [BlockPos].
 */
public operator fun BlockPos.minus(other: BlockPos): BlockPos {
    return BlockPos(
        this.x - other.x,
        this.y - other.y,
        this.z - other.z
    )
}

/**
 * Multiplies a [BlockPos] and a [BlockPos].
 * This method is a shorthand for component wise multiplication.
 */
public operator fun BlockPos.times(other: BlockPos): BlockPos {
    return BlockPos(
        this.x * other.x,
        this.y * other.y,
        this.z * other.z
    )
}

/**
 * Negates a [BlockPos].
 */
public operator fun BlockPos.unaryMinus(): BlockPos {
    return BlockPos(
        -this.x,
        -this.y,
        -this.z
    )
}
//endregion

//region Type compatibility operator variations
/**
 * Adds a [org.joml.Vector3i] to a [net.minecraft.util.math.BlockPos].
 */
public operator fun BlockPos.plus(other: Vector3i): BlockPos {
    return BlockPos(
        this.x + other.x,
        this.y + other.y,
        this.z + other.z
    )
}

/**
 * Subtracts a [org.joml.Vector3i] from a [net.minecraft.util.math.BlockPos].
 */
public operator fun BlockPos.minus(other: BlockPos): BlockPos {
    return BlockPos(
        this.x - other.x,
        this.y - other.y,
        this.z - other.z
    )
}

/**
 * Multiplies a [org.joml.Vector3i] and a [net.minecraft.util.math.BlockPos].
 * This method is a shorthand for component wise multiplication.
 */
public operator fun BlockPos.times(other: BlockPos): BlockPos {
    return BlockPos(
        this.x * other.x,
        this.y * other.y,
        this.z * other.z
    )
}

/**
 * Adds a [net.minecraft.util.math.Vec3i] to a [net.minecraft.util.math.BlockPos].
 */
public operator fun BlockPos.plus(other: Vec3i): BlockPos {
    return BlockPos(
        this.x + other.x,
        this.y + other.y,
        this.z + other.z
    )
}

/**
 * Subtracts a [net.minecraft.util.math.Vec3i] from a [net.minecraft.util.math.BlockPos].
 */
public operator fun BlockPos.minus(other: BlockPos): BlockPos {
    return BlockPos(
        this.x - other.x,
        this.y - other.y,
        this.z - other.z
    )
}

/**
 * Multiplies a [net.minecraft.util.math.Vec3i] and a [net.minecraft.util.math.BlockPos].
 * This method is a shorthand for component wise multiplication.
 */
public operator fun BlockPos.times(other: BlockPos): BlockPos {
    return BlockPos(
        this.x * other.x,
        this.y * other.y,
        this.z * other.z
    )
}
//endregion

//region Vector specific operators
/**
 * The [`x`][BlockPos.x] of a [BlockPos].
 */
public operator fun BlockPos.component1(): Int {
    return this.x
}

/**
 * The [`y`][BlockPos.y] of a [BlockPos].
 */
public operator fun BlockPos.component2(): Int {
    return this.y
}

/**
 * The [`z`][BlockPos.z] of a [BlockPos].
 */
public operator fun BlockPos.component3(): Int {
    return this.z
}
//endregion

//region Conversion methods
/**
 * Converts a [BlockPos] to a [org.joml.Vector3i].
 */
public fun BlockPos.toVector3i(): org.joml.Vector3i {
    return Vector3i(
        this.x,
        this.y,
        this.z
    )
}

/**
 * Converts a [BlockPos] to a [net.minecraft.util.math.Vec3i].
 */
public fun BlockPos.toVec3i(): net.minecraft.util.math.Vec3i {
    return Vec3i(
        this.x,
        this.y,
        this.z
    )
}
//endregion
