//
// DO NOT EDIT MANUALLY | THIS FILE WAS GENERATED BY https://github.com/SilverAndro/qkl_math_codegen
//

package org.quiltmc.qkl.library.math

import org.joml.Vector3d

/**
 * Adds a [Vector3d] to a [Vector3d].
 */
public operator fun Vector3d.plus(other: Vector3d): Vector3d {
    
}

/**
 * Subtracts a [Vector3d] from a [Vector3d].
 */
public operator fun Vector3d.minus(other: Vector3d): Vector3d {
    
}

/**
 * Multiplies a [Vector3d] and a [Vector3d].
 */
public operator fun Vector3d.times(other: Vector3d): Vector3d {
    
}

/**
 * Divides a [Vector3d] and a [Vector3d].
 */
public operator fun Vector3d.div(other: Vector3d): Vector3d {
    
}

/**
 * Negates a [Vector3d].
 */
public operator fun Vector3d.unaryMinus(): Vector3d {
    
}

