//
// DO NOT EDIT MANUALLY | THIS FILE WAS GENERATED BY https://github.com/SilverAndro/qkl_math_codegen
//

package org.quiltmc.qkl.library.math

import org.joml.Vector2i

//region Standard math operators
/**
 * Adds a [Vector2i] to a [Vector2i].
 */
public operator fun Vector2i.plus(other: Vector2i): Vector2i {
    return Vector2i(
        this.x + other.x,
        this.y + other.y
    )
}

/**
 * Subtracts a [Vector2i] from a [Vector2i].
 */
public operator fun Vector2i.minus(other: Vector2i): Vector2i {
    return Vector2i(
        this.x - other.x,
        this.y - other.y
    )
}

/**
 * Multiplies a [Vector2i] and a [Vector2i].
 */
public operator fun Vector2i.times(other: Vector2i): Vector2i {
    return Vector2i(
        this.x * other.x,
        this.y * other.y
    )
}

/**
 * Divides a [Vector2i] and a [Vector2i].
 */
public operator fun Vector2i.div(other: Vector2i): Vector2i {
    return Vector2i(
        this.x / other.x,
        this.y / other.y
    )
}

/**
 * Negates a [Vector2i].
 */
public operator fun Vector2i.unaryMinus(): Vector2i {
    return Vector2i(
        -this.x,
        -this.y
    )
}

//endregion
