//
// DO NOT EDIT MANUALLY | THIS FILE WAS GENERATED BY https://github.com/SilverAndro/qkl_math_codegen
//

package org.quiltmc.qkl.library.math

import org.joml.Vector2f

/**
 * Adds a [Vector2f] to a [Vector2f].
 */
public operator fun Vector2f.plus(other: Vector2f): Vector2f {
    
}

/**
 * Subtracts a [Vector2f] from a [Vector2f].
 */
public operator fun Vector2f.minus(other: Vector2f): Vector2f {
    
}

/**
 * Multiplies a [Vector2f] and a [Vector2f].
 */
public operator fun Vector2f.times(other: Vector2f): Vector2f {
    
}

/**
 * Divides a [Vector2f] and a [Vector2f].
 */
public operator fun Vector2f.div(other: Vector2f): Vector2f {
    
}

/**
 * Negates a [Vector2f].
 */
public operator fun Vector2f.unaryMinus(): Vector2f {
    
}

