//
// DO NOT EDIT MANUALLY | THIS FILE WAS GENERATED BY https://github.com/SilverAndro/qkl_math_codegen
//

package org.quiltmc.qkl.library.math

import org.joml.Vector4d

/**
 * Adds a [Vector4d] to a [Vector4d].
 */
public operator fun Vector4d.plus(other: Vector4d): Vector4d {
    
}

/**
 * Subtracts a [Vector4d] from a [Vector4d].
 */
public operator fun Vector4d.minus(other: Vector4d): Vector4d {
    
}

/**
 * Multiplies a [Vector4d] and a [Vector4d].
 */
public operator fun Vector4d.times(other: Vector4d): Vector4d {
    
}

/**
 * Divides a [Vector4d] and a [Vector4d].
 */
public operator fun Vector4d.div(other: Vector4d): Vector4d {
    
}

/**
 * Negates a [Vector4d].
 */
public operator fun Vector4d.unaryMinus(): Vector4d {
    
}

